/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mathe
 */
public class conversorMassa extends javax.swing.JFrame {
    
    double result, valor;
    String caixa1, caixa2, unidade;

    /**
     * Creates new form conversorMassa
     */
    public conversorMassa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        digite = new javax.swing.JTextField();
        box1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        box2 = new javax.swing.JComboBox<>();
        converter = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Conversor de Massas");

        jLabel2.setText("Digite aqui o valor a ser convertido:");

        digite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digiteActionPerformed(evt);
            }
        });

        box1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Valor 1", "Quilograma", "Hectograma", "Decagrama", "Grama", "Quilate", "Centigrama", "Miligrama" }));
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Para");

        box2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Valor 2", "Quilograma", "Hectograma", "Decagrama", "Grama", "Quilate", "Centigrama", "Miligrama" }));

        converter.setText("Converter");
        converter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultado da conversão:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(digite))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(box1, 0, 89, Short.MAX_VALUE)
                            .addComponent(converter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(limpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultado))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(digite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(converter)
                    .addComponent(limpar))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1ActionPerformed

    private void digiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digiteActionPerformed

    private void converterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterActionPerformed
        // TODO add your handling code here:
        caixa1 = box1.getSelectedItem().toString();
        caixa2 = box2.getSelectedItem().toString();
        valor = Double.valueOf(digite.getText());
        
        switch(caixa1){
            case "Quilograma":
                if(caixa2 == "Quilograma"){
                    result = valor;
                }
                if(caixa2 == "Hectograma"){
                    result = valor * 10.0;
                }
                if(caixa2 == "Decagrama"){
                    result = valor * 100.0;
                }
                if(caixa2 == "Grama"){
                    result = valor * 1000.0;
                }
                if(caixa2 == "Quilate"){
                    result = valor * 5000.0;
                }
                if(caixa2 == "Centigrama"){
                    result = valor * 100000.0;
                }
                if(caixa2 == "Miligrama"){
                    result = valor * 1000000.0;
                }
                break;
                
            case "Hectograma":
                if(caixa2 == "Quilograma"){
                    result = valor / 10;
                }
                if(caixa2 == "Hectograma"){
                    result = valor;
                }
                if(caixa2 == "Decagrama"){
                    result = valor * 10.0;
                }
                if(caixa2 == "Grama"){
                    result = valor * 100.0;
                }
                if(caixa2 == "Quilate"){
                    result = valor * 500.0;
                }
                if(caixa2 == "Centigrama"){
                    result = valor * 10000.0;
                }
                if(caixa2 == "Miligrama"){
                    result = valor * 100000.0;
                }
                break;
                
            case "Decagrama":
                if(caixa2 == "Quilograma"){
                    result = valor / 100.0;
                }
                if(caixa2 == "Hectograma"){
                    result = valor / 10.0;
                }
                if(caixa2 == "Decagrama"){
                    result = valor;
                }
                if(caixa2 == "Grama"){
                    result = valor * 10.0;
                }
                if(caixa2 == "Quilate"){
                    result = valor * 50.0;
                }
                if(caixa2 == "Centigrama"){
                    result = valor * 1000.0;
                }
                if(caixa2 == "Miligrama"){
                    result = valor * 10000.0;
                }
                break;
                
            case "Grama":
                if(caixa2 == "Quilograma"){
                    result = valor / 1000.0;
                }
                if(caixa2 == "Hectograma"){
                    result = valor / 100.0;
                }
                if(caixa2 == "Decagrama"){
                    result = valor / 10.0;
                }
                if(caixa2 == "Grama"){
                    result = valor;
                }
                if(caixa2 == "Quilate"){
                    result = valor * 5.0;
                }
                if(caixa2 == "Centigrama"){
                    result = valor * 100.0;
                }
                if(caixa2 == "Miligrama"){
                    result = valor * 1000.0;
                }
                break;
                
            case "Quilate":
                if(caixa2 == "Quilograma"){
                    result = valor / 5000.0;
                }
                if(caixa2 == "Hectograma"){
                    result = valor / 500.0;
                }
                if(caixa2 == "Decagrama"){
                    result = valor / 50.0;
                }
                if(caixa2 == "Grama"){
                    result = valor / 5.0;
                }
                if(caixa2 == "Quilate"){
                    result = valor;
                }
                if(caixa2 == "Centigrama"){
                    result = valor * 20.0;
                }
                if(caixa2 == "Miligrama"){
                    result = valor * 200.0;
                }
                break;
                
            case "Centigrama":
                if(caixa2 == "Quilograma"){
                    result = valor / 100000.0;
                }
                if(caixa2 == "Hectograma"){
                    result = valor / 10000.0;
                }
                if(caixa2 == "Decagrama"){
                    result = valor / 1000.0;
                }
                if(caixa2 == "Grama"){
                    result = valor / 100.0;
                }
                if(caixa2 == "Quilate"){
                    result = valor / 20.0;
                }
                if(caixa2 == "Centigrama"){
                    result = valor;
                }
                if(caixa2 == "Miligrama"){
                    result = valor * 10.0;
                }
                break;
                
            case "Miligrama":
                if(caixa2 == "Quilograma"){
                    result = valor / 1000000.0;
                }
                if(caixa2 == "Hectograma"){
                    result = valor / 100000.0;
                }
                if(caixa2 == "Decagrama"){
                    result = valor / 10000.0;
                }
                if(caixa2 == "Grama"){
                    result = valor / 1000.0;
                }
                if(caixa2 == "Quilate"){
                    result = valor / 100.0;
                }
                if(caixa2 == "Centigrama"){
                    result = valor / 10.0;
                }
                if(caixa2 == "Miligrama"){
                    result = valor;
                }
                break;
        }
        
        if(caixa2 == "Quilograma"){
            unidade = " Quilogramas";
        }
        if(caixa2 == "Hectograma"){
            unidade = " Hectogramas";
        }
        if(caixa2 == "Decagrama"){
            unidade = " Decagramas";
        }
        if(caixa2 == "Grama"){
            unidade = " Gramas";
        }
        if(caixa2 == "Quilate"){
            unidade = " Quilates";
        }
        if(caixa2 == "Centigrama"){
            unidade = " Centigramas";
        }
        if(caixa2 == "Miligrama"){
            unidade = " Miligramas";
        }
        
        resultado.setText(String.valueOf(result)+unidade);
    }//GEN-LAST:event_converterActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        digite.setText("");
        resultado.setText("");
        box1.setSelectedItem("Valor 1");
        box2.setSelectedItem("Valor 2");
    }//GEN-LAST:event_limparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversorMassa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversorMassa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversorMassa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversorMassa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversorMassa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box1;
    private javax.swing.JComboBox<String> box2;
    private javax.swing.JButton converter;
    private javax.swing.JTextField digite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
